USE [master]
GO
/****** Object:  Database [AgroZam]    Script Date: 26/02/2021 12:45:14 p. m. ******/
CREATE DATABASE [AgroZam]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AgroZam', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AgroZam.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AgroZam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AgroZam_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AgroZam] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AgroZam].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AgroZam] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AgroZam] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AgroZam] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AgroZam] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AgroZam] SET ARITHABORT OFF 
GO
ALTER DATABASE [AgroZam] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AgroZam] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AgroZam] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AgroZam] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AgroZam] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AgroZam] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AgroZam] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AgroZam] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AgroZam] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AgroZam] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AgroZam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AgroZam] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AgroZam] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AgroZam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AgroZam] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AgroZam] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AgroZam] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AgroZam] SET RECOVERY FULL 
GO
ALTER DATABASE [AgroZam] SET  MULTI_USER 
GO
ALTER DATABASE [AgroZam] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AgroZam] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AgroZam] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AgroZam] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AgroZam] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AgroZam] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AgroZam', N'ON'
GO
ALTER DATABASE [AgroZam] SET QUERY_STORE = OFF
GO
USE [AgroZam]
GO
/****** Object:  Schema [Compras]    Script Date: 26/02/2021 12:45:14 p. m. ******/
CREATE SCHEMA [Compras]
GO
/****** Object:  Schema [RH]    Script Date: 26/02/2021 12:45:14 p. m. ******/
CREATE SCHEMA [RH]
GO
/****** Object:  Schema [Sales]    Script Date: 26/02/2021 12:45:14 p. m. ******/
CREATE SCHEMA [Sales]
GO
/****** Object:  Table [RH].[Ciudades]    Script Date: 26/02/2021 12:45:14 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RH].[Ciudades](
	[idCiudad] [int] NOT NULL,
	[nombre] [varchar](80) NOT NULL,
	[idEstado] [int] NOT NULL,
	[estatus] [char](10) NOT NULL,
 CONSTRAINT [PK_RH.Ciudades] PRIMARY KEY CLUSTERED 
(
	[idCiudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AgroZam] SET  READ_WRITE 
GO
  CREATE TABLE  Turnos (
  [idTurno] [int] Primary key  NOT NULL,
  [nombre] [varchar] (20),
  [horaInicio] [time],
  [horaFin][time],
  [dias][varchar](30),
  );
  
