/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import conexion.ConexionBD;
import conexion.AsistenciaDAO;
import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.RH_Asistencia;
/**
 *
 * @author Carlos EsparzadeAnda
 */
public class AddAsistenciaFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAsistenciaFrame
     */
    ConexionBD conexion;
    RH_Asistencia asistencia;
    Boolean isNew;
    public AddAsistenciaFrame(ConexionBD conexion) {
        initComponents();
        this.conexion = conexion;
        this.isNew = true;
    }
    AddAsistenciaFrame (ConexionBD conexion, RH_Asistencia asistencia){
        initComponents();
        this.asistencia = asistencia;
        this.conexion = conexion;
        this.isNew = false;
        tmp_HoraInicio.setTime(asistencia.getHoraEntrada().toLocalTime());
        tmp_HoraFinal.setTime(asistencia.getHoraSalida().toLocalTime());
        tmp_Fecha.setDate(asistencia.getFecha().toLocalDate());
        llenarDias(asistencia.getDia());
        verificaCampos();
    }
        public void llenarDias(String dias) {
        String[] days = dias.split(",");
        for (String d : days) {
            switch (d) {
                case "LUNES":
                    rbLunes.setSelected(true);
                    break;
                case "MARTES":
                    rbMartes.setSelected(true);
                    break;
                case "MIÉRCOLES":
                    rbMiercoles.setSelected(true);
                    break;
                case "JUEVES":
                    rbJueves.setSelected(true);
                    break;
                case "VIERNES":
                    rbViernes.setSelected(true);
                    break;
                case "SÁBADO":
                    rbSabado.setSelected(true);
                    break;
                case "DOMINGO":
                    rbDomingo.setSelected(true);
                    break;
            }
        }

    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMiercoles = new javax.swing.JRadioButton();
        rbJueves = new javax.swing.JRadioButton();
        rbViernes = new javax.swing.JRadioButton();
        rbSabado = new javax.swing.JRadioButton();
        rbDomingo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tmp_HoraInicio = new com.github.lgooddatepicker.components.TimePicker();
        tmp_HoraFinal = new com.github.lgooddatepicker.components.TimePicker();
        tmp_Fecha = new com.github.lgooddatepicker.components.DatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_RealizarOperacion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(241, 151, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbLunes.setBackground(new java.awt.Color(241, 151, 89));
        rbLunes.setText("Lunes");
        jPanel2.add(rbLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        rbMartes.setBackground(new java.awt.Color(241, 151, 89));
        rbMartes.setText("Martes");
        jPanel2.add(rbMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        rbMiercoles.setBackground(new java.awt.Color(241, 151, 89));
        rbMiercoles.setText("Miercoles");
        jPanel2.add(rbMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        rbJueves.setBackground(new java.awt.Color(241, 151, 89));
        rbJueves.setText("Jueves");
        rbJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuevesActionPerformed(evt);
            }
        });
        jPanel2.add(rbJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        rbViernes.setBackground(new java.awt.Color(241, 151, 89));
        rbViernes.setText("Viernes ");
        jPanel2.add(rbViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        rbSabado.setBackground(new java.awt.Color(241, 151, 89));
        rbSabado.setText("Sabado");
        jPanel2.add(rbSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        rbDomingo.setBackground(new java.awt.Color(241, 151, 89));
        rbDomingo.setText("Domingo");
        rbDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDomingoActionPerformed(evt);
            }
        });
        jPanel2.add(rbDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, 280));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Días:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        tmp_HoraInicio.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(tmp_HoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 170, -1));

        tmp_HoraFinal.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(tmp_HoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 170, -1));

        tmp_Fecha.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(tmp_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Hora Entrada:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Hora Salida:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        btn_RealizarOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ope.png"))); // NOI18N
        btn_RealizarOperacion.setBorderPainted(false);
        btn_RealizarOperacion.setContentAreaFilled(false);
        btn_RealizarOperacion.setEnabled(false);
        btn_RealizarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RealizarOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RealizarOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 190, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Asistencia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnAtras.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 90));

        lblmensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJuevesActionPerformed

    private void rbDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDomingoActionPerformed

    private void btn_RealizarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RealizarOperacionActionPerformed
        RH_Asistencia nAsistencia = new RH_Asistencia();
        if(!isNew){
            nAsistencia.setIdAsistencia(asistencia.getIdAsistencia());
        }
        nAsistencia.setFecha(Date.valueOf(tmp_Fecha.getDate()));
        nAsistencia.setHoraEntrada(Time.valueOf(tmp_HoraInicio.getTime()));
        nAsistencia.setHoraSalida(Time.valueOf(tmp_HoraFinal.getTime()));
   
        String dias[] = new String[7];

        if (rbLunes.isSelected()) {
            dias[0] = "LUNES";
        }
        if (rbMartes.isSelected()) {
            dias[1] = "MARTES";
        }
        if (rbMiercoles.isSelected()) {
            dias[2] = "MIÉRCOLES";
        }
        if (rbJueves.isSelected()) {
            dias[3] = "JUEVES";
        }
        if (rbViernes.isSelected()) {
            dias[4] = "VIERNES";
        }
        if (rbSabado.isSelected()) {
            dias[5] = "SÁBADO";
        }
        if (rbDomingo.isSelected()) {
            dias[6] = "DOMINGO";
        }
        ArrayList<String> days = new ArrayList<>();

        for (int i = 0; i < 7; i++) {
            if (dias[i] != null) {
                days.add(dias[i]);
            }
        }
        String SEPARADOR = "";
        StringBuilder cadena = new StringBuilder();
        for (String s : days) {
            cadena.append(SEPARADOR);
            cadena.append(s);
            SEPARADOR = ",";
        }
        String diasT = cadena.toString();
        nAsistencia.setDia(diasT);
        AsistenciaDAO dao = new AsistenciaDAO(this.conexion);
        try {
            if (isNew) {
                if (dao.insertarAsistencia(nAsistencia)) {
                    JOptionPane.showMessageDialog(null, "Asistencia añadido con exito");
                    AsistenciasFrame asistenciasFrame = new AsistenciasFrame(this.conexion);
                    this.dispose();
                    asistenciasFrame.setVisible(true);
                    this.pack();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al intentar crear la Asistencia");
                }
            } else {
                if (dao.actualizarAsistencia(nAsistencia)) {
                    JOptionPane.showMessageDialog(null, "Asistencia actualizada con exito");
                    AsistenciasFrame asistenciasFrame = new AsistenciasFrame(this.conexion);
                    this.dispose();
                    asistenciasFrame.setVisible(true);
                    this.pack();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al intentar crear la asistencia");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error ");
        }
    }//GEN-LAST:event_btn_RealizarOperacionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        AsistenciasFrame asistencias = new AsistenciasFrame(this.conexion);
        this.dispose();
        asistencias.setVisible(true);
        asistencias.pack();
    }//GEN-LAST:event_btnRegresarActionPerformed

        public void verificaCampos() {
        if (verificaDias() && verificaFecha()&& verificaHora()) {
            btn_RealizarOperacion.setEnabled(true);
            lblmensaje.setText("");
        } else {
            if (!verificaDias()) {
                lblmensaje.setText("Debe seleccionar un Dia al menos \n");
            }
            if (!verificaHora()) {
                lblmensaje.setText("La hora de Inicio debe de ser anterior a la final \n");
            }
            if (!verificaFecha()) {
                lblmensaje.setText("Debe seleccionar una fecha correcta \n");
            }
            btn_RealizarOperacion.setEnabled(false);
        }
    }
        
    public boolean verificaDias() {
        return rbLunes.isSelected() || rbMartes.isSelected() || rbMiercoles.isSelected() || rbJueves.isSelected() || rbViernes.isSelected() || rbSabado.isSelected() || rbDomingo.isSelected();
    }
    public boolean verificaFecha(){
        if (tmp_Fecha.getDate() != null){
            return true;
        }
        return false;
    }

    public boolean verificaHora() {
        if (tmp_HoraInicio.getTime() != null && tmp_HoraFinal.getTime() != null) {
            return tmp_HoraInicio.getTime().isBefore(tmp_HoraFinal.getTime());
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_RealizarOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JRadioButton rbDomingo;
    private javax.swing.JRadioButton rbJueves;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMiercoles;
    private javax.swing.JRadioButton rbSabado;
    private javax.swing.JRadioButton rbViernes;
    private com.github.lgooddatepicker.components.DatePicker tmp_Fecha;
    private com.github.lgooddatepicker.components.TimePicker tmp_HoraFinal;
    private com.github.lgooddatepicker.components.TimePicker tmp_HoraInicio;
    // End of variables declaration//GEN-END:variables
}
