/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.AsistenciaDAO;
import conexion.ConexionBD;
import conexion.EmpleadoDAO;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.RH_Asistencia;
import modelo.RH_Empleado;

/**
 *
 * @author Mino
 */
public class AddAsistenciaFrame extends javax.swing.JFrame {

    ConexionBD conexion;
    RH_Asistencia asistencia;
    Boolean isNew;
    ArrayList<RH_Empleado> empleados;

    /**
     * Creates new form AddPuestos
     */
    public AddAsistenciaFrame(ConexionBD conexion) {
        initComponents();
        this.conexion = conexion;
        lbl_Titulo.setText("Añadir Asistencia");
        btn_Realizar.setText("");
        this.isNew = true;

    }

    public AddAsistenciaFrame(ConexionBD conexion, RH_Asistencia asistencia) {
        initComponents();
        this.asistencia = asistencia;
        this.conexion = conexion;
        lbl_Titulo.setText("Modificar Asistencia");
        btn_Realizar.setText("");
        btn_Realizar.setEnabled(true);
        this.isNew = false;
        dp_Fecha.setDate(asistencia.getFecha().toLocalDate());
        tp_HoraEntrada.setTime(asistencia.getHoraEntrada().toLocalTime());
        try {
            tp_HoraSalida.setTime(asistencia.getHoraSalida().toLocalTime());

        } catch (NullPointerException e) {
            tp_HoraSalida.setTime(LocalTime.now());
        }

        for (int i = 1; i < cmb_Dia.getItemCount(); i++) {
            if (cmb_Dia.getItemAt(i).equals(asistencia.getDia())) {
                cmb_Dia.setSelectedIndex(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Realizar = new javax.swing.JButton();
        btn_Atras = new javax.swing.JButton();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Mensaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dp_Fecha = new com.github.lgooddatepicker.components.DatePicker();
        jLabel4 = new javax.swing.JLabel();
        tp_HoraSalida = new com.github.lgooddatepicker.components.TimePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tp_HoraEntrada = new com.github.lgooddatepicker.components.TimePicker();
        cmb_Dia = new javax.swing.JComboBox<>();
        cmb_Empleado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_Empleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Realizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ope.png"))); // NOI18N
        btn_Realizar.setBorderPainted(false);
        btn_Realizar.setContentAreaFilled(false);
        btn_Realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RealizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Realizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnAtras.png"))); // NOI18N
        btn_Atras.setBorderPainted(false);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 260, 110));

        lbl_Titulo.setText("Realizar Operación");
        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));
        jPanel1.add(lbl_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 280, 40));

        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        dp_Fecha.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(dp_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel4.setText("Asistencias");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        jPanel1.add(tp_HoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, -1));

        jLabel1.setText("Hora Entrada");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel2.setText("Hora Salida");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, 30));
        jPanel1.add(tp_HoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 180, -1));

        cmb_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione día", "LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SÁBADO" }));
        jPanel1.add(cmb_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 180, -1));

        cmb_Empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado" }));
        cmb_Empleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_EmpleadoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmb_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 180, -1));

        jLabel5.setText("Dia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 30, -1));

        jLabel6.setText("Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));
        jPanel1.add(lbl_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RealizarActionPerformed
        RH_Asistencia nAsistencia = new RH_Asistencia();
        nAsistencia.setFecha(java.sql.Date.valueOf(dp_Fecha.getDate()));
        nAsistencia.setHoraEntrada(java.sql.Time.valueOf(tp_HoraEntrada.getTime()));
        nAsistencia.setHoraSalida(java.sql.Time.valueOf(tp_HoraSalida.getTime()));
        nAsistencia.setDia(cmb_Dia.getItemAt(cmb_Dia.getSelectedIndex()));
        nAsistencia.setEmpleado(empleados.get(cmb_Empleado.getSelectedIndex() - 1));
        nAsistencia.setEstatus("A");
        AsistenciaDAO dao = new AsistenciaDAO(this.conexion);

        if (isNew) {
            if (dao.insertarAsistencia(nAsistencia)) {
                JOptionPane.showMessageDialog(null, "Asistencia añadida con exito");
                AsistenciasFrame asistenciaFrame = new AsistenciasFrame(this.conexion);
                this.dispose();
                asistenciaFrame.setVisible(true);
                this.pack();
            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                AsistenciasFrame asistenciaFrame = new AsistenciasFrame(this.conexion);
                this.dispose();
                asistenciaFrame.setVisible(true);
                this.pack();
            }
        } else {
            nAsistencia.setIdAsistencia(this.asistencia.getIdAsistencia());
            if (dao.actualizarAsistencia(nAsistencia)) {
                JOptionPane.showMessageDialog(null, "Asistencia Modificado con exito");
                AsistenciasFrame asistenciaFrame = new AsistenciasFrame(this.conexion);
                this.dispose();
                asistenciaFrame.setVisible(true);
                this.pack();
            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                AsistenciasFrame asistenciaFrame = new AsistenciasFrame(this.conexion);
                this.dispose();
                asistenciaFrame.setVisible(true);
                this.pack();
            }
        }

    }//GEN-LAST:event_btn_RealizarActionPerformed

    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        AsistenciasFrame asistencias = new AsistenciasFrame(this.conexion);
        this.dispose();
        asistencias.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_AtrasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        EmpleadoDAO daoEmpleado = new EmpleadoDAO(this.conexion);
        empleados = daoEmpleado.consultaEmpleadosVista();
        empleados.forEach((e) -> {
            cmb_Empleado.addItem(e.getNombreCompleto());
            if (!isNew) {
                if (e.getNombreCompleto().equals(asistencia.getEmpleado().getNombreCompleto())) {
                    cmb_Empleado.setSelectedIndex(empleados.indexOf(e) + 1);
                }
            }
        });
    }//GEN-LAST:event_formWindowOpened

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        verificaCampos();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void cmb_EmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_EmpleadoItemStateChanged

    }//GEN-LAST:event_cmb_EmpleadoItemStateChanged

    private void verificaCampos() {
        try {

            LocalDate date = LocalDate.now();
            if ((dp_Fecha.getDate().isBefore(date) || dp_Fecha.getDate().isEqual(date)) && (tp_HoraEntrada.getTime().isBefore(tp_HoraSalida.getTime())) && cmb_Empleado.getSelectedIndex() > 0 && cmb_Dia.getSelectedIndex() > 0) {
                lbl_Mensaje.setText("");
                btn_Realizar.setEnabled(true);
            } else {
                lbl_Mensaje.setText("Debe completar los campos de manera correcta");
                btn_Realizar.setEnabled(false);
            }
        } catch (NullPointerException ex) {
            btn_Realizar.setEnabled(false);
            lbl_Mensaje.setText("Debe de completar los campos correctamente");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_Realizar;
    private javax.swing.JComboBox<String> cmb_Dia;
    private javax.swing.JComboBox<String> cmb_Empleado;
    private com.github.lgooddatepicker.components.DatePicker dp_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Empleado;
    private javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JLabel lbl_Titulo;
    private com.github.lgooddatepicker.components.TimePicker tp_HoraEntrada;
    private com.github.lgooddatepicker.components.TimePicker tp_HoraSalida;
    // End of variables declaration//GEN-END:variables
}
