/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import conexion.DepartamentoDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.RH_Departamento;
/**
 *
 * @author selen
 */
public class AddDepartamento extends javax.swing.JFrame {
  ConexionBD conexion;
    RH_Departamento depa;
    Boolean bandera;
    /**
     * Creates new form AddDepartamento
     */
    public AddDepartamento(ConexionBD conexion) {
       initComponents();
        this.conexion = conexion;
        tblTitulo.setText("Agregar Departamento");
        btnRealizar.setText("");
        this.bandera = false;
    }

    public AddDepartamento (ConexionBD conexion, RH_Departamento depa) {
        initComponents();
        this.depa = depa;
        this.conexion = conexion;
        tblTitulo.setText("Agregar Departamento");
        btnRealizar.setText("");
        btnRealizar.setEnabled(true);
        txtNombre.setText(this.depa.getNombre());
        this.bandera = true;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        tblTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRealizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 244, -1, 10));

        txtNombre.setBackground(new java.awt.Color(153, 255, 153));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 143, -1));
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 274, 187, 25));

        tblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblTitulo.setText("Agregar Departamento");
        jPanel1.add(tblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 40));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnAtras.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 228, -1));

        btnRealizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/btnGuardar.png"))); // NOI18N
        btnRealizar.setContentAreaFilled(false);
        btnRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRealizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarActionPerformed
        RH_Departamento ndepa = new RH_Departamento();
        ndepa.setNombre(txtNombre.getText().toUpperCase());
        ndepa.setEstatus("A");
        DepartamentoDAO depaDAO = new DepartamentoDAO(this.conexion);
        try {
            if (bandera) {
                ndepa.setIdDepartamento(this.depa.getIdDepartamento());
                if (depaDAO.actualizarDepartamento(ndepa)) {
                    JOptionPane.showMessageDialog(null,  " Departamento Modificado con exito");
                    DepartamentoFrame depa = new DepartamentoFrame(this.conexion);
                    this.dispose();
                    depa.setVisible(true);
                    this.pack();
                }
            } else {
                if (depaDAO.insertarDepartamento(ndepa)) {
                    JOptionPane.showMessageDialog(null, "Departamento Añadido con exito");
                    DepartamentoFrame depa = new DepartamentoFrame(this.conexion);
                    this.dispose();
                    depa.setVisible(true);
                    this.pack();
                }
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error:" + e.getMessage());
        }

    }//GEN-LAST:event_btnRealizarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        verificarCampos();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        DeduccionesFrame depa = new DeduccionesFrame(this.conexion);
        this.dispose();
        depa.setVisible(true);
        depa.pack();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    
      public void verificarCampos() {
        if ("".equals(txtNombre.getText())) {
            btnRealizar.setEnabled(false);
            lblMensaje.setText("Debe llenar los campos");
        } else {
            btnRealizar.setEnabled(true);
            lblMensaje.setText("");
        }

    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddDepartamento().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel tblTitulo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
