/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import conexion.EmpleadoDAO;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Marco Chavez
 */
public class AddEmpleadoFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEmpleadoFrame
     */
    InputStream fotografia;
    ConexionBD conexion;

    public AddEmpleadoFrame(ConexionBD conexion) {
        initComponents();

        this.conexion = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tp_DatosEmpleado = new javax.swing.JTabbedPane();
        lp_DatosPersonales = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        txf_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_ApellidoPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_ApellidoMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_Sexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dp_FechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jLabel7 = new javax.swing.JLabel();
        txf_Curp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmb_EstadoCivil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txf_NSS = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btn_Fotografia = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cmb_Escolaridad = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txf_Especialidad = new javax.swing.JTextField();
        lbImage = new javax.swing.JLabel();
        btn_Subir = new javax.swing.JButton();
        bnt_Guardar = new javax.swing.JButton();
        ftf_NSS = new javax.swing.JFormattedTextField();
        lp_Domicilio = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        txf_Direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmb_Ciudad = new javax.swing.JComboBox<>();
        txf_CodigoPostal = new javax.swing.JTextField();
        txf_Colonia = new javax.swing.JTextField();
        lp_DatosEmpresa = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        txf_DiasVacaciones = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dp_FechaContratacion = new com.github.lgooddatepicker.components.DatePicker();
        cmb_Turno = new javax.swing.JComboBox<>();
        cmb_Sucursal = new javax.swing.JComboBox<>();
        cmb_Departamento = new javax.swing.JComboBox<>();
        cmb_Puesto = new javax.swing.JComboBox<>();
        txf_DiasPermiso = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txff_SalarioDiario = new javax.swing.JFormattedTextField();
        cmb_Tipo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        lp_Login = new javax.swing.JLayeredPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txff_Email = new javax.swing.JFormattedTextField();
        pf_Password = new javax.swing.JPasswordField();
        pf_PasswordConfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));

        jLabel2.setText("Nombre");

        txf_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido Paterno ");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Sexo");

        cmb_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SU SEXO", "MASCULINO", "FEMENINO" }));

        jLabel6.setText("Fecha de Nacimiento");

        jLabel7.setText("CURP");

        jLabel8.setText("Estado Civil");

        cmb_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SU ESTADO CIVIL", "SOLTERO", "CASADO", "DIVORCIADO", "VIUDO", "CONCUBINATO" }));

        jLabel1.setText("NSS");

        txf_NSS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txf_NSSFocusLost(evt);
            }
        });

        jLabel25.setText("Fotografia");

        btn_Fotografia.setText("Seleccionar..");
        btn_Fotografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FotografiaActionPerformed(evt);
            }
        });

        jLabel26.setText("Escolaridad");

        cmb_Escolaridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SU ESCOLARIDAD", "SECUNDARIA", "PREPARATORIA", "LICENCIATURA", "POSGRADO" }));

        jLabel27.setText("Especialidad");

        btn_Subir.setText("Subir");
        btn_Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubirActionPerformed(evt);
            }
        });

        bnt_Guardar.setText("Sigu");
        bnt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_GuardarActionPerformed(evt);
            }
        });

        ftf_NSS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftf_NSSFocusLost(evt);
            }
        });

        lp_DatosPersonales.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(txf_Nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(txf_ApellidoPaterno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(txf_ApellidoMaterno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(cmb_Sexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(dp_FechaNacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(txf_Curp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(cmb_EstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(txf_NSS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(btn_Fotografia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(cmb_Escolaridad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(txf_Especialidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(lbImage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(btn_Subir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(bnt_Guardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosPersonales.setLayer(ftf_NSS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_DatosPersonalesLayout = new javax.swing.GroupLayout(lp_DatosPersonales);
        lp_DatosPersonales.setLayout(lp_DatosPersonalesLayout);
        lp_DatosPersonalesLayout.setHorizontalGroup(
            lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                            .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lp_DatosPersonalesLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(40, 40, 40))
                                .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(92, 92, 92)))
                            .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txf_Nombre)
                                .addComponent(txf_ApellidoPaterno)))
                        .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                            .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(41, 41, 41)
                            .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txf_ApellidoMaterno)))
                        .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(dp_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(72, 72, 72)
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_Curp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Fotografia)
                                            .addComponent(btn_Subir))
                                        .addGap(26, 26, 26))
                                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftf_NSS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txf_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(23, 23, 23)
                        .addComponent(cmb_Escolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(txf_NSS, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lp_DatosPersonalesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnt_Guardar)
                .addGap(198, 198, 198))
        );
        lp_DatosPersonalesLayout.setVerticalGroup(
            lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txf_NSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txf_ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftf_NSS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txf_ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(btn_Fotografia))))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Subir)))
                .addGap(2, 2, 2)
                .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Escolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(lp_DatosPersonalesLayout.createSequentialGroup()
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dp_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txf_Curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txf_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(lp_DatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addComponent(bnt_Guardar)
                .addContainerGap())
        );

        tp_DatosEmpleado.addTab("Datos Personales", lp_DatosPersonales);

        jLabel9.setText("Direccion");

        jLabel10.setText("Colonia");

        jLabel11.setText("Codigo Postal");

        jLabel12.setText("Ciudad");

        lp_Domicilio.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(txf_Direccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(cmb_Ciudad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(txf_CodigoPostal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(txf_Colonia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_DomicilioLayout = new javax.swing.GroupLayout(lp_Domicilio);
        lp_Domicilio.setLayout(lp_DomicilioLayout);
        lp_DomicilioLayout.setHorizontalGroup(
            lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DomicilioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txf_Direccion)
                    .addComponent(txf_Colonia)
                    .addComponent(txf_CodigoPostal)
                    .addComponent(cmb_Ciudad, 0, 237, Short.MAX_VALUE))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        lp_DomicilioLayout.setVerticalGroup(
            lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txf_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txf_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txf_CodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmb_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(831, Short.MAX_VALUE))
        );

        tp_DatosEmpleado.addTab("Domicilio", lp_Domicilio);

        jLabel13.setText("Dias Vacaciones");

        jLabel14.setText("Dias Permiso");

        jLabel15.setText("Departamento");

        jLabel16.setText("Puesto");

        jLabel17.setText("Sucursal");

        jLabel18.setText("Turno");

        jLabel19.setText("Fecha Contratación");

        jLabel20.setText("Salario Diario");

        cmb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Tipo");

        lp_DatosEmpresa.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(txf_DiasVacaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(dp_FechaContratacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Turno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Sucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Departamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Puesto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(txf_DiasPermiso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(txff_SalarioDiario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Tipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_DatosEmpresaLayout = new javax.swing.GroupLayout(lp_DatosEmpresa);
        lp_DatosEmpresa.setLayout(lp_DatosEmpresaLayout);
        lp_DatosEmpresaLayout.setHorizontalGroup(
            lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addGap(76, 76, 76)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dp_FechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                        .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_DiasPermiso, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txf_DiasVacaciones))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txff_SalarioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        lp_DatosEmpresaLayout.setVerticalGroup(
            lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txf_DiasVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txff_SalarioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txf_DiasPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmb_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmb_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmb_Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmb_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dp_FechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 694, Short.MAX_VALUE)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap())
        );

        tp_DatosEmpleado.addTab("Datos Empresa", lp_DatosEmpresa);

        jLabel22.setText("E-Mail");

        jLabel23.setText("Contraseña");

        jLabel24.setText("Confirma Contraseña");

        lp_Login.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(txff_Email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(pf_Password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(pf_PasswordConfirm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_LoginLayout = new javax.swing.GroupLayout(lp_Login);
        lp_Login.setLayout(lp_LoginLayout);
        lp_LoginLayout.setHorizontalGroup(
            lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_LoginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(40, 40, 40)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pf_PasswordConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pf_Password)
                    .addComponent(txff_Email))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        lp_LoginLayout.setVerticalGroup(
            lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_LoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txff_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(pf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(pf_PasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(843, Short.MAX_VALUE))
        );

        tp_DatosEmpleado.addTab("Ingreso", lp_Login);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(tp_DatosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addComponent(tp_DatosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_NombreActionPerformed

    private void btn_FotografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FotografiaActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        try {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            File f = new File(ruta);
            InputStream inputStream = new DataInputStream(new FileInputStream(f));
            this.fotografia = inputStream;
        } catch (NullPointerException e) {
            System.out.println("No se ha seleccionado ningún fichero");
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_FotografiaActionPerformed

    private void btn_SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubirActionPerformed
        EmpleadoDAO dao = new EmpleadoDAO(this.conexion);
        dao.insertarPrueba(fotografia);
        InputStream inputStream;
        inputStream = dao.consultaFotografia(3);
        Image imagen;
        try {
            imagen = ImageIO.read(inputStream);
//            BufferedImage bi = this.createResizedCopy(imagen, 400, 400, true);
//            imagen = (Image)bi;
            ImageIcon imgIcon = new ImageIcon(imagen);
            Image imgEscalada = imgIcon.getImage().getScaledInstance(lbImage.getWidth(),
                    lbImage.getHeight(), Image.SCALE_SMOOTH);
            Icon iconoEscalado = new ImageIcon(imgEscalada);
            lbImage.setIcon(iconoEscalado);

        } catch (IOException ex) {
            Logger.getLogger(AddEmpleadoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_SubirActionPerformed

    private void bnt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_GuardarActionPerformed

    }//GEN-LAST:event_bnt_GuardarActionPerformed

    private void txf_NSSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txf_NSSFocusLost


    }//GEN-LAST:event_txf_NSSFocusLost

    private void ftf_NSSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftf_NSSFocusLost

        System.out.println(String.valueOf(ftf_NSS.getValue()));
    }//GEN-LAST:event_ftf_NSSFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            MaskFormatter mskNSS = new MaskFormatter("###-####-####");
            mskNSS.install(ftf_NSS);
        } catch (ParseException err) {

        }
    }//GEN-LAST:event_formWindowOpened
    BufferedImage createResizedCopy(Image originalImage, int scaledWidth, int scaledHeight, boolean preserveAlpha) {
        int imageType = preserveAlpha ? BufferedImage.TYPE_INT_RGB : BufferedImage.TYPE_INT_ARGB;
        BufferedImage scaledBI = new BufferedImage(scaledWidth, scaledHeight, imageType);
        Graphics2D g = scaledBI.createGraphics();
        if (preserveAlpha) {
            g.setComposite(AlphaComposite.Src);
        }
        g.drawImage(originalImage, 0, 0, scaledWidth, scaledHeight, null);
        g.dispose();
        return scaledBI;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Guardar;
    private javax.swing.JButton btn_Fotografia;
    private javax.swing.JButton btn_Subir;
    private javax.swing.JComboBox<String> cmb_Ciudad;
    private javax.swing.JComboBox<String> cmb_Departamento;
    private javax.swing.JComboBox<String> cmb_Escolaridad;
    private javax.swing.JComboBox<String> cmb_EstadoCivil;
    private javax.swing.JComboBox<String> cmb_Puesto;
    private javax.swing.JComboBox<String> cmb_Sexo;
    private javax.swing.JComboBox<String> cmb_Sucursal;
    private javax.swing.JComboBox<String> cmb_Tipo;
    private javax.swing.JComboBox<String> cmb_Turno;
    private com.github.lgooddatepicker.components.DatePicker dp_FechaContratacion;
    private com.github.lgooddatepicker.components.DatePicker dp_FechaNacimiento;
    private javax.swing.JFormattedTextField ftf_NSS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLayeredPane lp_DatosEmpresa;
    private javax.swing.JLayeredPane lp_DatosPersonales;
    private javax.swing.JLayeredPane lp_Domicilio;
    private javax.swing.JLayeredPane lp_Login;
    private javax.swing.JPasswordField pf_Password;
    private javax.swing.JPasswordField pf_PasswordConfirm;
    private javax.swing.JTabbedPane tp_DatosEmpleado;
    private javax.swing.JTextField txf_ApellidoMaterno;
    private javax.swing.JTextField txf_ApellidoPaterno;
    private javax.swing.JTextField txf_CodigoPostal;
    private javax.swing.JTextField txf_Colonia;
    private javax.swing.JTextField txf_Curp;
    private javax.swing.JTextField txf_DiasPermiso;
    private javax.swing.JTextField txf_DiasVacaciones;
    private javax.swing.JTextField txf_Direccion;
    private javax.swing.JTextField txf_Especialidad;
    private javax.swing.JTextField txf_NSS;
    private javax.swing.JTextField txf_Nombre;
    private javax.swing.JFormattedTextField txff_Email;
    private javax.swing.JFormattedTextField txff_SalarioDiario;
    // End of variables declaration//GEN-END:variables
}
