/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.CiudadDAO;
import conexion.ConexionBD;
import conexion.DepartamentoDAO;
import conexion.EmpleadoDAO;
import conexion.EstadoDAO;
import conexion.PuestoDAO;
import conexion.SucursalesDAO;
import conexion.TurnosDAO;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Date;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.MaskFormatter;
import modelo.Compras_Sucursal;
import modelo.RH_Ciudad;
import modelo.RH_Departamento;
import modelo.RH_Empleado;
import modelo.RH_Estado;
import modelo.RH_Puesto;
import modelo.RH_Turno;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Marco Chavez
 */
public class AddEmpleadoFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEmpleadoFrame
     */
    byte[] fotografia;
    ConexionBD conexion;
    RH_Empleado empleado;

    DepartamentoDAO daoDepartamento;
    PuestoDAO daoPuesto;
    CiudadDAO daoCiudad;
    SucursalesDAO daoSucursal;
    TurnosDAO daoTurno;

    EstadoDAO daoEstado;

    ArrayList<RH_Departamento> departamentos;
    ArrayList<RH_Puesto> puestos;
    ArrayList<RH_Ciudad> ciudades;
    ArrayList<Compras_Sucursal> sucursales;
    ArrayList<RH_Turno> turnos;
    ArrayList<RH_Estado> estados;
    Boolean isNew;
    Integer bandera = 0;

    public AddEmpleadoFrame(ConexionBD conexion) {
        initComponents();
         this.setLocationRelativeTo(null);
        this.conexion = conexion;
        this.isNew = true;

    }

    public AddEmpleadoFrame(ConexionBD conexion, RH_Empleado empleado) {
        initComponents();
        this.conexion = conexion;
        this.isNew = false;
        this.empleado = empleado;
        this.fotografia = empleado.getFotografia();
        this.txf_Nombre.setText(empleado.getNombre());
        this.txf_ApellidoPaterno.setText(empleado.getApellidoPaterno());
        this.txf_ApellidoMaterno.setText(empleado.getApellidoMaterno());
        this.ftf_NSS.setValue(empleado.getNss());
        this.ftf_CURP.setValue(empleado.getCurp());
        this.dp_FechaNacimiento.setDate(empleado.getFechaNacimiento().toLocalDate());
        this.txf_Especialidad.setText(empleado.getEspecialidad());
        txf_Direccion.setText(empleado.getDireccion());
        txf_Colonia.setText(empleado.getColonia());
        ftf_CodigoPostal.setValue(empleado.getCodigoPostal());
        sp_diasVacaciones.setValue(empleado.getDiasVacaciones());
        sp_diasPermiso.setValue(empleado.getDiasPermiso());
        sp_SalarioDiario.setValue(empleado.getSalarioDiario());
        dp_FechaContratacion.setDate(empleado.getFechaContratacion().toLocalDate());
        ftf_Email.setText(empleado.getEmail());
        pf_Password.setText(empleado.getPassword());
        pf_PasswordConfirm.setText(empleado.getPassword());

        if ("MASCULINO".equals(empleado.getSexo())) {
            cmb_Sexo.setSelectedIndex(1);
        } else {
            cmb_Sexo.setSelectedIndex(2);
        }

        for (int i = 1; i <= cmb_Escolaridad.getItemCount(); i++) {
            if (empleado.getEscolaridad().equals(cmb_Escolaridad.getItemAt(i))) {
                cmb_Escolaridad.setSelectedIndex(i);
            }
        }

        for (int i = 1; i <= cmb_EstadoCivil.getItemCount(); i++) {
            if (empleado.getEstadoCivil().equals(cmb_EstadoCivil.getItemAt(i))) {
                cmb_EstadoCivil.setSelectedIndex(i);
            }
        }
        for (int i = 1; i <= cmb_Tipo.getItemCount(); i++) {
            if (empleado.getTipo().equals(cmb_Tipo.getItemAt(i))) {
                cmb_Tipo.setSelectedIndex(i);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_RealizarOperacion = new javax.swing.JButton();
        tp_DatosEmpleado = new javax.swing.JTabbedPane();
        lp_DatosPersonales = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        txf_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_ApellidoPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_ApellidoMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_Sexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dp_FechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmb_EstadoCivil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_Seleccionar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cmb_Escolaridad = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txf_Especialidad = new javax.swing.JTextField();
        lbImage = new javax.swing.JLabel();
        ftf_NSS = new javax.swing.JFormattedTextField();
        ftf_CURP = new javax.swing.JFormattedTextField();
        lbl_MensajeDatosPersonales = new javax.swing.JLabel();
        lp_Domicilio = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        txf_Direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmb_Ciudad = new javax.swing.JComboBox<>();
        txf_Colonia = new javax.swing.JTextField();
        cmb_Estado = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        ftf_CodigoPostal = new javax.swing.JFormattedTextField();
        lbl_MensajeDatosDomicilio = new javax.swing.JLabel();
        lp_DatosEmpresa = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dp_FechaContratacion = new com.github.lgooddatepicker.components.DatePicker();
        cmb_Turno = new javax.swing.JComboBox<>();
        cmb_Sucursal = new javax.swing.JComboBox<>();
        cmb_Departamento = new javax.swing.JComboBox<>();
        cmb_Puesto = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cmb_Tipo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        sp_diasVacaciones = new javax.swing.JSpinner();
        sp_diasPermiso = new javax.swing.JSpinner();
        sp_SalarioDiario = new javax.swing.JSpinner();
        lbl_MensajeDatosEmpresa = new javax.swing.JLabel();
        lbl_Salario = new javax.swing.JLabel();
        lp_Login = new javax.swing.JLayeredPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ftf_Email = new javax.swing.JFormattedTextField();
        pf_Password = new javax.swing.JPasswordField();
        pf_PasswordConfirm = new javax.swing.JPasswordField();
        lbl_MensajeDatosSistema = new javax.swing.JLabel();
        btn_Atras = new javax.swing.JButton();
        lbl_Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 547));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_RealizarOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ope.png"))); // NOI18N
        btn_RealizarOperacion.setBorderPainted(false);
        btn_RealizarOperacion.setContentAreaFilled(false);
        btn_RealizarOperacion.setEnabled(false);
        btn_RealizarOperacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_RealizarOperacionMouseMoved(evt);
            }
        });
        btn_RealizarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RealizarOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RealizarOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, 180, 70));

        tp_DatosEmpleado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tp_DatosEmpleadoPropertyChange(evt);
            }
        });

        lp_DatosPersonales.setBackground(new java.awt.Color(153, 255, 153));
        lp_DatosPersonales.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lp_DatosPersonalesMouseMoved(evt);
            }
        });
        lp_DatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        lp_DatosPersonales.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        txf_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NombreActionPerformed(evt);
            }
        });
        lp_DatosPersonales.add(txf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 11, 154, -1));

        jLabel3.setText("Apellido Paterno ");
        lp_DatosPersonales.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 49, -1, -1));
        lp_DatosPersonales.add(txf_ApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 49, 154, -1));

        jLabel4.setText("Apellido Materno");
        lp_DatosPersonales.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));
        lp_DatosPersonales.add(txf_ApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 75, 162, -1));

        jLabel5.setText("Sexo");
        lp_DatosPersonales.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        cmb_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SU SEXO", "MASCULINO", "FEMENINO" }));
        lp_DatosPersonales.add(cmb_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 138, -1, -1));

        jLabel6.setText("Fecha de Nacimiento");
        lp_DatosPersonales.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));
        lp_DatosPersonales.add(dp_FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 184, -1, -1));

        jLabel7.setText("CURP");
        lp_DatosPersonales.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 234, -1, -1));

        jLabel8.setText("Estado Civil");
        lp_DatosPersonales.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, -1, -1));

        cmb_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SU ESTADO CIVIL", "SOLTERO", "CASADO", "DIVORCIADO", "VIUDO", "CONCUBINATO" }));
        lp_DatosPersonales.add(cmb_EstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 270, -1, -1));

        jLabel1.setText("NSS");
        lp_DatosPersonales.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 14, -1, -1));

        jLabel25.setText("Fotografia");
        lp_DatosPersonales.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 75, -1, -1));

        btn_Seleccionar.setText("Seleccionar..");
        btn_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarActionPerformed(evt);
            }
        });
        lp_DatosPersonales.add(btn_Seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 71, -1, -1));

        jLabel26.setText("Escolaridad");
        lp_DatosPersonales.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 184, -1, -1));

        cmb_Escolaridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE SU ESCOLARIDAD", "SECUNDARIA", "PREPARATORIA", "LICENCIATURA", "POSGRADO" }));
        lp_DatosPersonales.add(cmb_Escolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 181, -1, -1));

        jLabel27.setText("Especialidad");
        lp_DatosPersonales.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 234, -1, -1));
        lp_DatosPersonales.add(txf_Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 231, 196, -1));
        lp_DatosPersonales.add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 49, 84, 77));

        ftf_NSS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftf_NSSFocusLost(evt);
            }
        });
        lp_DatosPersonales.add(ftf_NSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 11, 264, -1));

        ftf_CURP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftf_CURPFocusLost(evt);
            }
        });
        lp_DatosPersonales.add(ftf_CURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 231, 291, -1));
        lp_DatosPersonales.add(lbl_MensajeDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 372, 433, 26));

        tp_DatosEmpleado.addTab("Datos Personales", lp_DatosPersonales);

        lp_Domicilio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lp_DomicilioMouseMoved(evt);
            }
        });

        jLabel9.setText("Direccion");

        jLabel10.setText("Colonia");

        jLabel11.setText("Codigo Postal");

        jLabel12.setText("Ciudad");

        cmb_Ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Ciudad" }));
        cmb_Ciudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CiudadItemStateChanged(evt);
            }
        });

        cmb_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Estado" }));
        cmb_Estado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_EstadoItemStateChanged(evt);
            }
        });

        jLabel28.setText("Estado");

        lp_Domicilio.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(txf_Direccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(cmb_Ciudad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(txf_Colonia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(cmb_Estado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(ftf_CodigoPostal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Domicilio.setLayer(lbl_MensajeDatosDomicilio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_DomicilioLayout = new javax.swing.GroupLayout(lp_Domicilio);
        lp_Domicilio.setLayout(lp_DomicilioLayout);
        lp_DomicilioLayout.setHorizontalGroup(
            lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DomicilioLayout.createSequentialGroup()
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_DomicilioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel28))
                        .addGap(24, 24, 24)
                        .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_Direccion)
                            .addComponent(txf_Colonia)
                            .addComponent(cmb_Ciudad, 0, 237, Short.MAX_VALUE)
                            .addComponent(cmb_Estado, 0, 237, Short.MAX_VALUE)
                            .addComponent(ftf_CodigoPostal)))
                    .addGroup(lp_DomicilioLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbl_MensajeDatosDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        lp_DomicilioLayout.setVerticalGroup(
            lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txf_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txf_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ftf_CodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(lp_DomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(lbl_MensajeDatosDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        tp_DatosEmpleado.addTab("Domicilio", lp_Domicilio);

        lp_DatosEmpresa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lp_DatosEmpresaMouseMoved(evt);
            }
        });
        lp_DatosEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lp_DatosEmpresaFocusGained(evt);
            }
        });

        jLabel13.setText("Dias Vacaciones");

        jLabel14.setText("Dias Permiso");

        jLabel15.setText("Departamento");

        jLabel16.setText("Puesto");

        jLabel17.setText("Sucursal");

        jLabel18.setText("Turno");

        jLabel19.setText("Fecha Contratación");

        cmb_Turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un turno" }));

        cmb_Sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Sucursal" }));

        cmb_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un departamento" }));

        cmb_Puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un puesto" }));
        cmb_Puesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_PuestoItemStateChanged(evt);
            }
        });

        jLabel20.setText("Salario Diario");

        cmb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo", "ADMINISTRADOR", "EMPLEADO", "TI" }));

        jLabel29.setText("Tipo de Empleado");

        sp_diasVacaciones.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 1));

        sp_diasPermiso.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 1));

        sp_SalarioDiario.setModel(new javax.swing.SpinnerNumberModel(100.0f, 0.0f, null, 0.01f));

        lbl_Salario.setText("jLabel21");

        lp_DatosEmpresa.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(dp_FechaContratacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Turno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Sucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Departamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Puesto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(cmb_Tipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(sp_diasVacaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(sp_diasPermiso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(sp_SalarioDiario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(lbl_MensajeDatosEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_DatosEmpresa.setLayer(lbl_Salario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_DatosEmpresaLayout = new javax.swing.GroupLayout(lp_DatosEmpresa);
        lp_DatosEmpresa.setLayout(lp_DatosEmpresaLayout);
        lp_DatosEmpresaLayout.setHorizontalGroup(
            lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                        .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(76, 76, 76)
                        .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dp_FechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sp_diasPermiso, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(sp_diasVacaciones))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel20)
                                .addGap(41, 41, 41)
                                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp_SalarioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Salario)))))
                    .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbl_MensajeDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        lp_DatosEmpresaLayout.setVerticalGroup(
            lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_DatosEmpresaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20)
                    .addComponent(sp_diasVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_SalarioDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sp_diasPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Salario))
                .addGap(26, 26, 26)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmb_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmb_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmb_Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmb_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dp_FechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(lp_DatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(62, 62, 62)
                .addComponent(lbl_MensajeDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        tp_DatosEmpleado.addTab("Datos Empresa", lp_DatosEmpresa);

        lp_Login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lp_LoginMouseMoved(evt);
            }
        });

        jLabel22.setText("E-Mail");

        jLabel23.setText("Contraseña");

        jLabel24.setText("Confirma Contraseña");

        lp_Login.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(ftf_Email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(pf_Password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(pf_PasswordConfirm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_Login.setLayer(lbl_MensajeDatosSistema, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_LoginLayout = new javax.swing.GroupLayout(lp_Login);
        lp_Login.setLayout(lp_LoginLayout);
        lp_LoginLayout.setHorizontalGroup(
            lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_LoginLayout.createSequentialGroup()
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_LoginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addGap(40, 40, 40)
                        .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf_PasswordConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(pf_Password)
                            .addComponent(ftf_Email)))
                    .addGroup(lp_LoginLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbl_MensajeDatosSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        lp_LoginLayout.setVerticalGroup(
            lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_LoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ftf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(pf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(pf_PasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(lbl_MensajeDatosSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        tp_DatosEmpleado.addTab("Ingreso al Sistema", lp_Login);

        jPanel1.add(tp_DatosEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnAtras.png"))); // NOI18N
        btn_Atras.setBorderPainted(false);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        lbl_Titulo.setText("Añadir Empleado al Sistema");
        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 15, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_NombreActionPerformed

    private void btn_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        //Filtro del filechooser   
        fileChooser.setFileFilter(new FileNameExtensionFilter("Imagenes", "jpg", "png"));
        fileChooser.showOpenDialog(fileChooser);
        try {
            FileInputStream inputStream = new FileInputStream(fileChooser.getSelectedFile());
            fotografia = FileUtils.readFileToByteArray(fileChooser.getSelectedFile());
            Image imagen;
            try {
                imagen = ImageIO.read(inputStream);
                ImageIcon imgIcon = new ImageIcon(imagen);
                Image imgEscalada = imgIcon.getImage().getScaledInstance(lbImage.getWidth(),
                        lbImage.getHeight(), Image.SCALE_SMOOTH);
                Icon iconoEscalado = new ImageIcon(imgEscalada);
                lbImage.setIcon(iconoEscalado);
            } catch (IOException ex) {
                Logger.getLogger(AddEmpleadoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (NullPointerException e) {
            System.out.println("No se ha seleccionado ningún fichero");
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(AddEmpleadoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SeleccionarActionPerformed

    private void ftf_NSSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftf_NSSFocusLost

    }//GEN-LAST:event_ftf_NSSFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            daoDepartamento = new DepartamentoDAO(this.conexion);
            daoPuesto = new PuestoDAO(this.conexion);
            daoCiudad = new CiudadDAO(this.conexion);
            daoTurno = new TurnosDAO(this.conexion);
            daoEstado = new EstadoDAO(this.conexion);
            daoSucursal = new SucursalesDAO(this.conexion);
            MaskFormatter mskNSS = new MaskFormatter("###########");
            mskNSS.install(ftf_NSS);
            MaskFormatter mskCURP = new MaskFormatter("UUUU######UUUUUU##");
            mskCURP.install(ftf_CURP);
            MaskFormatter mskCP = new MaskFormatter("#####");
            mskCP.install(ftf_CodigoPostal);
            estados = daoEstado.consultaEstadosVista();
            departamentos = daoDepartamento.consultaDepartamentosVista();
            puestos = daoPuesto.consultaPuestosVista();
            turnos = daoTurno.consultaTurnosVista();

            if (!isNew) {

                for (int i = 0; i < estados.size(); i++) {
                    cmb_Estado.addItem(estados.get(i).getNombre());
                    if (estados.get(i).getNombre().equals(empleado.getCiudad().getEstado().getNombre())) {
                        cmb_Estado.setSelectedIndex(i + 1);
                    }
                }
                this.ciudades = daoCiudad.consultarCiudadesEstadoVista(estados.get(cmb_Estado.getSelectedIndex() - 1).getIdEstado());
                for (int i = 0; i < ciudades.size(); i++) {
                    cmb_Ciudad.addItem(ciudades.get(i).getNombre());
                    try {
                        if ((ciudades.get(i).getNombre().equals(empleado.getCiudad().getNombre())) && !isNew) {
                            cmb_Ciudad.setSelectedIndex(i + 1);
                            bandera++;
                        }
                    } catch (Exception e) {
                    }
                }

                for (int i = 0; i < departamentos.size(); i++) {
                    cmb_Departamento.addItem(departamentos.get(i).getNombre());
                    if (departamentos.get(i).getNombre().equals(empleado.getDepartamento().getNombre())) {
                        cmb_Departamento.setSelectedIndex(i + 1);
                    }
                }

                for (int i = 0; i < puestos.size(); i++) {
                    cmb_Puesto.addItem(puestos.get(i).getNombre());
                    if (puestos.get(i).getNombre().equals(empleado.getPuesto().getNombre())) {
                        cmb_Puesto.setSelectedIndex(i + 1);
                    }
                }

                for (int i = 0; i < turnos.size(); i++) {
                    cmb_Turno.addItem(turnos.get(i).getNombre());
                    if (turnos.get(i).getNombre().equals(empleado.getTurno().getNombre())) {
                        cmb_Turno.setSelectedIndex(i + 1);
                    }
                }
                try {
                    ImageIcon imgIcon = new ImageIcon(this.fotografia);
                    Image imgEscalada = imgIcon.getImage().getScaledInstance(lbImage.getWidth(),
                            lbImage.getHeight(), Image.SCALE_SMOOTH);

                    Icon iconoEscalado = new ImageIcon(imgEscalada);
                    lbImage.setIcon(iconoEscalado);
                } catch (NullPointerException np) {
                    System.out.println("Null pointer " + np.getMessage());
                }

            } else {
                estados.forEach((s) -> {
                    cmb_Estado.addItem(s.getNombre());
                });

                departamentos.forEach((d) -> {
                    cmb_Departamento.addItem(d.getNombre());
                });
                puestos.forEach((p) -> {
                    cmb_Puesto.addItem(p.getNombre());
                });
                turnos.forEach((t) -> {
                    cmb_Turno.addItem(t.getNombre());
                });
            }

        } catch (ParseException err) {

        }
    }//GEN-LAST:event_formWindowOpened

    private void ftf_CURPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftf_CURPFocusLost
        ftf_CURP.getValue();
    }//GEN-LAST:event_ftf_CURPFocusLost

    private void cmb_EstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_EstadoItemStateChanged
        if (cmb_Estado.getSelectedIndex() > 0) {
            cmb_Ciudad.setEnabled(true);
            cmb_Ciudad.removeAllItems();
            cmb_Ciudad.addItem("Seleccione una ciudad");
            this.ciudades = daoCiudad.consultarCiudadesEstadoVista(estados.get(cmb_Estado.getSelectedIndex() - 1).getIdEstado());
            for (int i = 0; i < ciudades.size(); i++) {
                cmb_Ciudad.addItem(ciudades.get(i).getNombre());
            }
        } else {
            cmb_Ciudad.setEnabled(false);
        }

    }//GEN-LAST:event_cmb_EstadoItemStateChanged

    private void lp_DatosEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lp_DatosEmpresaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lp_DatosEmpresaFocusGained

    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        EmpleadosFrame empleados = new EmpleadosFrame(this.conexion);
        this.dispose();
        empleados.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_AtrasActionPerformed

    private void tp_DatosEmpleadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tp_DatosEmpleadoPropertyChange

    }//GEN-LAST:event_tp_DatosEmpleadoPropertyChange

    private void lp_DatosPersonalesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lp_DatosPersonalesMouseMoved
        if (verificaDatosPersonales()) {
            lbl_MensajeDatosPersonales.setText("");
        } else {
            lbl_MensajeDatosPersonales.setText("Debe completar los datos");
        }
        if (verificaDatosPersonales() && verificaDatosDomicilio() && verificaDatosEmpresa() && verificaDatosSistema()) {
            btn_RealizarOperacion.setEnabled(true);
            lbl_MensajeDatosPersonales.setText("");
        } else {

            btn_RealizarOperacion.setEnabled(false);
        }
    }//GEN-LAST:event_lp_DatosPersonalesMouseMoved

    private void btn_RealizarOperacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RealizarOperacionMouseMoved

    }//GEN-LAST:event_btn_RealizarOperacionMouseMoved

    private void lp_LoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lp_LoginMouseMoved

        if (verificaDatosSistema()) {
            lbl_MensajeDatosSistema.setText("");
        } else {
            lbl_MensajeDatosSistema.setText("Debe completar los datos");
        }
        if (verificaDatosPersonales() && verificaDatosDomicilio() && verificaDatosEmpresa() && verificaDatosSistema()) {
            btn_RealizarOperacion.setEnabled(true);
            lbl_MensajeDatosSistema.setText("");
        } else {
            btn_RealizarOperacion.setEnabled(false);
        }
    }//GEN-LAST:event_lp_LoginMouseMoved

    private void lp_DatosEmpresaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lp_DatosEmpresaMouseMoved

        if (verificaDatosEmpresa()) {
            lbl_MensajeDatosEmpresa.setText("");
        } else {
            lbl_MensajeDatosEmpresa.setText("Debe completar los datos");
        }
        if (verificaDatosPersonales() && verificaDatosDomicilio() && verificaDatosEmpresa() && verificaDatosSistema()) {
            btn_RealizarOperacion.setEnabled(true);
            lbl_MensajeDatosEmpresa.setText("");
        } else {

            btn_RealizarOperacion.setEnabled(false);
        }
    }//GEN-LAST:event_lp_DatosEmpresaMouseMoved

    private void lp_DomicilioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lp_DomicilioMouseMoved

        if (verificaDatosDomicilio()) {
            lbl_MensajeDatosDomicilio.setText("");
        } else {
            lbl_MensajeDatosDomicilio.setText("Debe completar los datos");
        }
        if (verificaDatosPersonales() && verificaDatosDomicilio() && verificaDatosEmpresa() && verificaDatosSistema()) {
            btn_RealizarOperacion.setEnabled(true);
            lbl_MensajeDatosDomicilio.setText("");
        } else {
            btn_RealizarOperacion.setEnabled(false);

        }

    }//GEN-LAST:event_lp_DomicilioMouseMoved

    private void btn_RealizarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RealizarOperacionActionPerformed
        RH_Empleado nEmpleado = new RH_Empleado();
        nEmpleado.setNombre(txf_Nombre.getText().toUpperCase());
        nEmpleado.setApellidoPaterno(txf_ApellidoPaterno.getText().toUpperCase());
        nEmpleado.setApellidoMaterno(txf_ApellidoMaterno.getText().toUpperCase());
        nEmpleado.setNss((String) ftf_NSS.getText());
        nEmpleado.setFotografia(this.fotografia);
        nEmpleado.setEscolaridad(cmb_Escolaridad.getItemAt(cmb_Escolaridad.getSelectedIndex()));
        nEmpleado.setSexo(cmb_Sexo.getItemAt(cmb_Sexo.getSelectedIndex()));
        nEmpleado.setFechaNacimiento(Date.valueOf(dp_FechaNacimiento.getDate()));
        nEmpleado.setEstadoCivil(cmb_EstadoCivil.getItemAt(cmb_EstadoCivil.getSelectedIndex()));
        nEmpleado.setCurp(ftf_CURP.getText());
        nEmpleado.setEspecialidad(txf_Especialidad.getText().toUpperCase());
        nEmpleado.setDireccion(txf_Direccion.getText().toUpperCase());
        nEmpleado.setColonia(txf_Colonia.getText().toUpperCase());
        nEmpleado.setCodigoPostal((String) ftf_CodigoPostal.getText());
        nEmpleado.setCiudad(new RH_Ciudad(ciudades.get(cmb_Ciudad.getSelectedIndex() - 1).getIdCiudad(), this.conexion));
        nEmpleado.setDiasVacaciones((Integer) sp_diasVacaciones.getValue());
        nEmpleado.setDiasPermiso((Integer) sp_diasPermiso.getValue());
        nEmpleado.setSalarioDiario((Float) sp_SalarioDiario.getValue());
        nEmpleado.setDepartamento(new RH_Departamento(departamentos.get(cmb_Departamento.getSelectedIndex() - 1).getIdDepartamento(), this.conexion));
        nEmpleado.setPuesto(new RH_Puesto(puestos.get(cmb_Puesto.getSelectedIndex() - 1).getIdPuesto(), this.conexion));
        nEmpleado.setSucursal(new Compras_Sucursal(sucursales.get(cmb_Sucursal.getSelectedIndex() - 1).getIdSucursal(), this.conexion));
        nEmpleado.setTurno(new RH_Turno(turnos.get(cmb_Turno.getSelectedIndex() - 1).getIdTurno(), this.conexion));
        nEmpleado.setFechaContratacion(Date.valueOf(dp_FechaContratacion.getDate()));
        nEmpleado.setTipo(cmb_Tipo.getItemAt(cmb_Tipo.getSelectedIndex()));
        nEmpleado.setEmail((String) ftf_Email.getText());
        nEmpleado.setPassword(pf_Password.getText().toUpperCase());
        nEmpleado.setEstatus("A");

        EmpleadoDAO dao = new EmpleadoDAO(this.conexion);
        if (!isNew) {
            nEmpleado.setIdEmpleado(this.empleado.getIdEmpleado());
            if (dao.actualizarEmpleado(nEmpleado)) {
                JOptionPane.showMessageDialog(null, " Empleado Modificado con exito");
                EmpleadosFrame empleados = new EmpleadosFrame(this.conexion);
                this.dispose();
                empleados.setVisible(true);
                this.pack();
            }

        } else {
            if (dao.insertarEmpleado(nEmpleado)) {
                JOptionPane.showMessageDialog(null, " Empleado Añadido con exito");
                EmpleadosFrame empleados = new EmpleadosFrame(this.conexion);
                this.dispose();
                empleados.setVisible(true);
                this.pack();
            }
        }
    }//GEN-LAST:event_btn_RealizarOperacionActionPerformed

    private void cmb_CiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CiudadItemStateChanged
        if (cmb_Ciudad.getSelectedIndex() > 0) {
            cmb_Sucursal.setEnabled(true);
            cmb_Sucursal.removeAllItems();
            cmb_Sucursal.addItem("Seleccione una Sucursal");
            sucursales = daoSucursal.consultaSucursalesVistaCiudad(ciudades.get(cmb_Ciudad.getSelectedIndex() - 1).getIdCiudad());
            for (int i = 0; i < sucursales.size(); i++) {
                cmb_Sucursal.addItem(sucursales.get(i).getNombre());
                try {
                    if ((sucursales.get(i).getNombre().equals(empleado.getSucursal().getNombre())) && !isNew) {
                        cmb_Sucursal.setSelectedIndex(i + 1);
                        bandera++;
                    }
                } catch (Exception e) {
                }
            }
        }


    }//GEN-LAST:event_cmb_CiudadItemStateChanged

    private void cmb_PuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_PuestoItemStateChanged
        if (cmb_Puesto.getSelectedIndex() > 0) {
            Float salarioMinimo = puestos.get(cmb_Puesto.getSelectedIndex() - 1).getSalarioMinimo();
            Float salarioMaximo = puestos.get(cmb_Puesto.getSelectedIndex() - 1).getSalarioMaximo();
            Float step = 0.01f;
            lbl_Salario.setText("El salario debe de estar en el rango de " + salarioMinimo + " y " + salarioMaximo);
            SpinnerNumberModel model1;
            if (!isNew) {
                Float salarioDiario = this.empleado.getSalarioDiario();
                model1 = new SpinnerNumberModel(salarioDiario, salarioMinimo, salarioMaximo, step);
            } else {
                model1 = new SpinnerNumberModel(salarioMinimo, salarioMinimo, salarioMaximo, step);
            }
            sp_SalarioDiario.setModel(model1);
        }
        else{
            lbl_Salario.setText("");
        }
    }//GEN-LAST:event_cmb_PuestoItemStateChanged
    BufferedImage createResizedCopy(Image originalImage, int scaledWidth, int scaledHeight, boolean preserveAlpha) {
        int imageType = preserveAlpha ? BufferedImage.TYPE_INT_RGB : BufferedImage.TYPE_INT_ARGB;
        BufferedImage scaledBI = new BufferedImage(scaledWidth, scaledHeight, imageType);
        Graphics2D g = scaledBI.createGraphics();
        if (preserveAlpha) {
            g.setComposite(AlphaComposite.Src);
        }
        g.drawImage(originalImage, 0, 0, scaledWidth, scaledHeight, null);
        g.dispose();
        return scaledBI;
    }

    public boolean verificaDatosSistema() {
        String EMAIL_PATTERN
                = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        if (ftf_Email.getText().matches(EMAIL_PATTERN) && (pf_Password.getText() == null ? pf_PasswordConfirm.getText() == null : pf_Password.getText().equals(pf_PasswordConfirm.getText()))) {
            return true;
        } else {
            return false;
        }
    }

    public boolean verificaDatosDomicilio() {
        return !"".equals(txf_Direccion.getText()) && !"".equals(txf_Colonia.getText()) && !"".equals(ftf_CodigoPostal.getText()) && cmb_Estado.getSelectedIndex() > 0 && cmb_Ciudad.getSelectedIndex() > 0;
    }

    public boolean verificaDatosPersonales() {
        LocalDate date = LocalDate.now();
        boolean bandera = false;
        try {
            bandera = !"".equals(txf_Nombre.getText()) && !"".equals(txf_ApellidoPaterno.getText()) && !"".equals(txf_ApellidoMaterno.getText()) && !"".equals(ftf_NSS.getText()) && cmb_Sexo.getSelectedIndex() != 0 && cmb_Escolaridad.getSelectedIndex() > 0 && !"".equals(ftf_CURP.getText()) && !"".equals(txf_Especialidad.getText()) && cmb_EstadoCivil.getSelectedIndex() > 0 && ((date.getYear() - dp_FechaNacimiento.getDate().getYear()) >= 18);
        } catch (Exception e) {
            bandera = false;
        }
        return bandera;
    }

    public boolean verificaDatosEmpresa() {
        LocalDate date = LocalDate.now();
        boolean bandera = false;
        try {
            bandera = (Integer) sp_diasVacaciones.getValue() >= 6 && (Integer) sp_diasPermiso.getValue() >= 6 && (Float) sp_SalarioDiario.getValue() >= 0 && cmb_Departamento.getSelectedIndex() > 0 && cmb_Puesto.getSelectedIndex() > 0 && cmb_Sucursal.getSelectedIndex() > 0 && cmb_Turno.getSelectedIndex() > 0 && cmb_Tipo.getSelectedIndex() > 0 && (dp_FechaContratacion.getDate().isBefore(date) || dp_FechaContratacion.getDate().isEqual(date));
        } catch (Exception e) {
            bandera = false;
        }
        return bandera;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_RealizarOperacion;
    private javax.swing.JButton btn_Seleccionar;
    private javax.swing.JComboBox<String> cmb_Ciudad;
    private javax.swing.JComboBox<String> cmb_Departamento;
    private javax.swing.JComboBox<String> cmb_Escolaridad;
    private javax.swing.JComboBox<String> cmb_Estado;
    private javax.swing.JComboBox<String> cmb_EstadoCivil;
    private javax.swing.JComboBox<String> cmb_Puesto;
    private javax.swing.JComboBox<String> cmb_Sexo;
    private javax.swing.JComboBox<String> cmb_Sucursal;
    private javax.swing.JComboBox<String> cmb_Tipo;
    private javax.swing.JComboBox<String> cmb_Turno;
    private com.github.lgooddatepicker.components.DatePicker dp_FechaContratacion;
    private com.github.lgooddatepicker.components.DatePicker dp_FechaNacimiento;
    private javax.swing.JFormattedTextField ftf_CURP;
    private javax.swing.JFormattedTextField ftf_CodigoPostal;
    private javax.swing.JFormattedTextField ftf_Email;
    private javax.swing.JFormattedTextField ftf_NSS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbl_MensajeDatosDomicilio;
    private javax.swing.JLabel lbl_MensajeDatosEmpresa;
    private javax.swing.JLabel lbl_MensajeDatosPersonales;
    private javax.swing.JLabel lbl_MensajeDatosSistema;
    private javax.swing.JLabel lbl_Salario;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLayeredPane lp_DatosEmpresa;
    private javax.swing.JLayeredPane lp_DatosPersonales;
    private javax.swing.JLayeredPane lp_Domicilio;
    private javax.swing.JLayeredPane lp_Login;
    private javax.swing.JPasswordField pf_Password;
    private javax.swing.JPasswordField pf_PasswordConfirm;
    private javax.swing.JSpinner sp_SalarioDiario;
    private javax.swing.JSpinner sp_diasPermiso;
    private javax.swing.JSpinner sp_diasVacaciones;
    private javax.swing.JTabbedPane tp_DatosEmpleado;
    private javax.swing.JTextField txf_ApellidoMaterno;
    private javax.swing.JTextField txf_ApellidoPaterno;
    private javax.swing.JTextField txf_Colonia;
    private javax.swing.JTextField txf_Direccion;
    private javax.swing.JTextField txf_Especialidad;
    private javax.swing.JTextField txf_Nombre;
    // End of variables declaration//GEN-END:variables
}
