/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import conexion.FormaPagoDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.RH_FormaPago;

/**
 *
 * @author Marco Chavez
 */
public class AddFormaPagoFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEstadoFrame
     */
    ConexionBD conexion;
    RH_FormaPago formaPago;
    Boolean bandera;

    public AddFormaPagoFrame(ConexionBD conexion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.conexion = conexion;
        lbl_Titulo.setText("Añadir Forma de Pago");
        this.bandera = false;
    }

    public AddFormaPagoFrame(ConexionBD conexion, RH_FormaPago formaPago) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.formaPago = formaPago;
        this.conexion = conexion;
        lbl_Main.setText("Modificar Forma de Pago");
        btn_Realizar.setEnabled(true);
        txf_Nombre.setText(this.formaPago.getNombre());
        this.bandera = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Realizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_Main = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_Nombre = new javax.swing.JTextField();
        lbl_Mensaje = new javax.swing.JLabel();
        lbl_Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Estado");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Realizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ope.png"))); // NOI18N
        btn_Realizar.setBorderPainted(false);
        btn_Realizar.setContentAreaFilled(false);
        btn_Realizar.setEnabled(false);
        btn_Realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RealizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Realizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnAtras.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 110));

        lbl_Main.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Main.setText("Formas Pago");
        jPanel1.add(lbl_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        txf_Nombre.setBackground(new java.awt.Color(153, 255, 153));
        txf_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NombreActionPerformed(evt);
            }
        });
        txf_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txf_NombreKeyReleased(evt);
            }
        });
        jPanel1.add(txf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 210, -1));
        jPanel1.add(lbl_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 180, 40));

        lbl_Titulo.setText("Añadir una forma de pago");
        jPanel1.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_NombreActionPerformed

    private void btn_RealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RealizarActionPerformed
        RH_FormaPago nFormaPago = new RH_FormaPago();
        nFormaPago.setNombre(txf_Nombre.getText().toUpperCase());
        nFormaPago.setEstatus("A");
        FormaPagoDAO daoFormaPago = new FormaPagoDAO(this.conexion);
        try {
            if (bandera) {
                nFormaPago.setIdFormaPago(this.formaPago.getIdFormaPago());
                if (daoFormaPago.actualizarFormaPago(nFormaPago)) {
                    JOptionPane.showMessageDialog(null, "Forma de Pago Modificada con exito");
                    FormasPagoFrame formaPago = new FormasPagoFrame(this.conexion);
                    this.dispose();
                    formaPago.setVisible(true);
                    this.pack();
                }
            } else {
                if (daoFormaPago.insertarFormaPago(nFormaPago)) {
                    JOptionPane.showMessageDialog(null, "Forma de Pago Añadida con exito");
                    FormasPagoFrame formaPago = new FormasPagoFrame(this.conexion);
                    this.dispose();
                    formaPago.setVisible(true);
                    this.pack();;
                }
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error:" + e.getMessage());
        }

    }//GEN-LAST:event_btn_RealizarActionPerformed

    private void txf_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_NombreKeyReleased
        verificarCampos();
    }//GEN-LAST:event_txf_NombreKeyReleased

    public void verificarCampos() {
        if ("".equals(txf_Nombre.getText())) {
            btn_Realizar.setEnabled(false);
            lbl_Mensaje.setText("Debe llenar los campos");
        } else {
            btn_Realizar.setEnabled(true);
            lbl_Mensaje.setText("");
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FormasPagoFrame formaPago = new FormasPagoFrame(this.conexion);
        this.dispose();
        formaPago.setVisible(true);
        this.pack();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Realizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Main;
    private javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JTextField txf_Nombre;
    // End of variables declaration//GEN-END:variables
}
