/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import conexion.TurnosDAO;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Time;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.RH_Turno;

/**
 *
 * @author selen
 */
public class AddTurnosFrame extends javax.swing.JFrame {

    ConexionBD conexion;
    RH_Turno turno;
    Boolean isNew;

    /**
     * Creates new form Turnos
     *
     * @param conexion
     */
    public AddTurnosFrame(ConexionBD conexion) {
        this.conexion = conexion;
        initComponents();
        TurnosDAO tunos = new TurnosDAO(this.conexion);
        ArrayList<RH_Turno> lista = tunos.consultaTurnosVista();
        this.isNew = true;

    }

    AddTurnosFrame(ConexionBD conexion, RH_Turno turno) {
        this.turno = turno;
        this.conexion = conexion;

        btn_Operacion.setText("Modificar Turno");
        btn_Operacion.setEnabled(true);
        txf_Nombre.setText(this.turno.getNombre());

        String dias = null;
        if (rbLunes.isSelected() == true) {
            dias = "Lunes";

        }
        if (rbMartes.isSelected() == true) {
            dias = "Martes";
        }
        if (rbMiercoles.isSelected() == true) {
            dias = "Miercoles";
        }
        if (rbJueves.isSelected() == true) {
            dias = "Jueves";
        }
        if (rbViernes.isSelected() == true) {
            dias = "Viernes";
        }
        if (rbSabado.isSelected() == true) {
            dias = "Sabado";
        }
        if (rbDomingo.isSelected() == true) {
            dias = "Domingo";
        }
        this.isNew = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txf_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMiercoles = new javax.swing.JRadioButton();
        rbJueves = new javax.swing.JRadioButton();
        rbViernes = new javax.swing.JRadioButton();
        rbSabado = new javax.swing.JRadioButton();
        btn_Operacion = new javax.swing.JButton();
        rbDomingo = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JButton();
        tmp_HoraInicio = new com.github.lgooddatepicker.components.TimePicker();
        tmp_HoraFin = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turnos");
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(241, 151, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, 340));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/Turnos.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 110));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, -1));

        txf_Nombre.setBackground(new java.awt.Color(153, 255, 153));
        txf_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txf_NombreKeyReleased(evt);
            }
        });
        jPanel2.add(txf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Hora Inicio;");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Hora Fin");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Días:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        rbLunes.setText("Lunes");
        rbLunes.setBackground(new java.awt.Color(241, 151, 89));
        rbLunes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(rbLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        rbMartes.setText("Martes");
        rbMartes.setBackground(new java.awt.Color(241, 151, 89));
        rbMartes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(rbMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        rbMiercoles.setBackground(new java.awt.Color(241, 151, 89));
        rbMiercoles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbMiercoles.setText("Miercoles");
        jPanel2.add(rbMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        rbJueves.setBackground(new java.awt.Color(241, 151, 89));
        rbJueves.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbJueves.setText("Jueves");
        rbJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuevesActionPerformed(evt);
            }
        });
        jPanel2.add(rbJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        rbViernes.setBackground(new java.awt.Color(241, 151, 89));
        rbViernes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbViernes.setText("Viernes");
        rbViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViernesActionPerformed(evt);
            }
        });
        jPanel2.add(rbViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        rbSabado.setBackground(new java.awt.Color(241, 151, 89));
        rbSabado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbSabado.setText("Sabado");
        jPanel2.add(rbSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        btn_Operacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/btnGuardar.png"))); // NOI18N
        btn_Operacion.setBorderPainted(false);
        btn_Operacion.setContentAreaFilled(false);
        btn_Operacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_OperacionMouseEntered(evt);
            }
        });
        btn_Operacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OperacionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 160, 80));

        rbDomingo.setBackground(new java.awt.Color(241, 151, 89));
        rbDomingo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbDomingo.setText("Domingo");
        jPanel2.add(rbDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/btnAtras.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));
        jPanel2.add(tmp_HoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));
        jPanel2.add(tmp_HoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OperacionActionPerformed
        RH_Turno nTurno = new RH_Turno();
        nTurno.setNombre(txf_Nombre.getText().toUpperCase());
        nTurno.setHoraInicio(Time.valueOf(tmp_HoraInicio.getTime()));
        nTurno.setHoraFin(Time.valueOf(tmp_HoraFin.getTime()));
        nTurno.setEstatus("A");
        String dias[] = new String[7];
        if (rbLunes.isSelected()) {
            dias[0] = "LUNES";
        }
        if (rbMartes.isSelected()) {
            dias[1] = "MARTES";
        }
        if (rbMiercoles.isSelected()) {
            dias[2] = "MIÉRCOLES";
        }
        if (rbJueves.isSelected()) {
            dias[3] = "JUEVES";
        }
        if (rbViernes.isSelected()) {
            dias[4] = "VIERNES";
        }
        if (rbSabado.isSelected()) {
            dias[5] = "SÁBADO";
        }
        if (rbDomingo.isSelected()) {
            dias[5] = "DOMINGO";
        }
        String diasT = "";
        for (int i = 0; i < 7; i++) {
            if (dias[i]!=null) {
                diasT += dias[i]+" ";
            }
        }
        nTurno.setDias(diasT);
        TurnosDAO dao = new TurnosDAO(this.conexion);
        try {
            if (isNew) {
                if (dao.insertarTurno(nTurno)) {
                    JOptionPane.showMessageDialog(null, "Turno añadido con exito");
                    TurnosFrame turnosFrame = new TurnosFrame(this.conexion);
                    this.dispose();
                    turnosFrame.setVisible(true);
                    this.pack();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al intentar crear el turno");
                }
            } else {

            }
        } catch (HeadlessException e) {

        }


    }//GEN-LAST:event_btn_OperacionActionPerformed

    private void rbJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJuevesActionPerformed

    private void rbViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbViernesActionPerformed

    private void btn_OperacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OperacionMouseEntered

    }//GEN-LAST:event_btn_OperacionMouseEntered

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        EstadosFrame estados = new EstadosFrame(this.conexion);
        this.dispose();
        estados.setVisible(true);
        estados.pack();

    }//GEN-LAST:event_btnRegresarActionPerformed
    public void verificaCampos(){

    }
    private void txf_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_NombreKeyReleased
        verificaCampos();
    }//GEN-LAST:event_txf_NombreKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_Operacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbDomingo;
    private javax.swing.JRadioButton rbJueves;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMiercoles;
    private javax.swing.JRadioButton rbSabado;
    private javax.swing.JRadioButton rbViernes;
    private com.github.lgooddatepicker.components.TimePicker tmp_HoraFin;
    private com.github.lgooddatepicker.components.TimePicker tmp_HoraInicio;
    private javax.swing.JTextField txf_Nombre;
    // End of variables declaration//GEN-END:variables
}
