/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import conexion.EmpleadoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.RH_Empleado;

/**
 *
 * @author Marco Chavez
 */
public class EmpleadosFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadosFrame
     */
    ConexionBD conexion;
    int paginaActual;
    int paginaMaxima;
    boolean banderaBusqueda = false;

    public EmpleadosFrame(ConexionBD conexion) {
        initComponents();
         this.setLocationRelativeTo(null);
        this.conexion = conexion;
        this.paginaActual = 1;
        EmpleadoDAO empleados = new EmpleadoDAO(this.conexion);
        this.paginaMaxima = empleados.consultaPaginas();
        lbl_PaginaMaxima.setText(String.valueOf(this.paginaMaxima));
        lbl_PaginaActual.setText(String.valueOf(this.paginaActual));
        ArrayList<RH_Empleado> lista = empleados.consultaEmpleadosVistaPaginada(paginaActual);
        llenarTabla(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorByte1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorByte();
        btn_Anterior = new javax.swing.JPanel();
        btn_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Datos = new javax.swing.JTable();
        btn_AddEmpleado = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_Atras = new javax.swing.JButton();
        btn_Siguiente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_PaginaActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_PaginaMaxima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Anterior.setBackground(new java.awt.Color(241, 151, 89));
        btn_Anterior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btn_Eliminar.png"))); // NOI18N
        btn_Eliminar.setBorderPainted(false);
        btn_Eliminar.setContentAreaFilled(false);
        btn_Eliminar.setEnabled(false);
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        btn_Anterior.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        tbl_Datos.setBackground(new java.awt.Color(153, 255, 153));
        tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdEmpleado", "Nombre Completo", "Direccion", "Departamento", "Puesto", "Ciudad", "Sucursal"
            }
        ));
        tbl_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_DatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Datos);

        btn_Anterior.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 1180, -1));

        btn_AddEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnGuardar.png"))); // NOI18N
        btn_AddEmpleado.setBorderPainted(false);
        btn_AddEmpleado.setContentAreaFilled(false);
        btn_AddEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddEmpleadoActionPerformed(evt);
            }
        });
        btn_Anterior.add(btn_AddEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btn_Modificar.png"))); // NOI18N
        btn_Modificar.setBorderPainted(false);
        btn_Modificar.setContentAreaFilled(false);
        btn_Modificar.setEnabled(false);
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });
        btn_Anterior.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Empleados");
        btn_Anterior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 60));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnAtras.png"))); // NOI18N
        btn_Atras.setBorderPainted(false);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });
        btn_Anterior.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/General/Sig.png"))); // NOI18N
        btn_Siguiente.setBorderPainted(false);
        btn_Siguiente.setContentAreaFilled(false);
        btn_Anterior.add(btn_Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 160, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/General/Ant.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        btn_Anterior.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 170, 40));

        lbl_PaginaActual.setText("1");
        btn_Anterior.add(lbl_PaginaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        jLabel3.setText("de");
        btn_Anterior.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, -1, -1));

        lbl_PaginaMaxima.setText("1");
        btn_Anterior.add(lbl_PaginaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 1710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddEmpleadoActionPerformed
        AddEmpleadoFrame addEmpleado = new AddEmpleadoFrame(this.conexion);
        this.dispose();
        addEmpleado.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_AddEmpleadoActionPerformed

    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        PrincipalFrame pf = new PrincipalFrame(this.conexion);
        this.dispose();
        pf.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_AtrasActionPerformed

    private void tbl_DatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DatosMousePressed
        btn_Modificar.setEnabled(true);
        btn_Eliminar.setEnabled(true);
    }//GEN-LAST:event_tbl_DatosMousePressed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        Integer idEmpleado = Integer.parseInt(tbl_Datos.getValueAt(tbl_Datos.getSelectedRow(), 0).toString());
        String nombre = tbl_Datos.getValueAt(tbl_Datos.getSelectedRow(), 1).toString();
        int reply = JOptionPane.showConfirmDialog(null, "Está seguro que desea eliminar el empleado '" + nombre + "'?", "Confirmar Cambio de estatus", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            RH_Empleado Empleado = new RH_Empleado();
            EmpleadoDAO DAO = new EmpleadoDAO(this.conexion);
            Empleado = DAO.consultaEmpleadoId(idEmpleado);
            if (DAO.eliminacionLogica(Empleado)) {
                JOptionPane.showMessageDialog(null, "Empleado Eliminado");
                ArrayList<RH_Empleado> lista = DAO.consultaEmpleadosVistaPaginada(this.paginaActual);
                llenarTabla(lista);
                btn_Modificar.setEnabled(false);
                btn_Eliminar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }

        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        Integer idEmpleado = Integer.parseInt(tbl_Datos.getValueAt(tbl_Datos.getSelectedRow(), 0).toString());
        RH_Empleado Empleado = new RH_Empleado();
        EmpleadoDAO DAO = new EmpleadoDAO(this.conexion);
        Empleado = DAO.consultaEmpleadoId(idEmpleado);
        AddEmpleadoFrame modificar = new AddEmpleadoFrame(this.conexion, Empleado);
        this.dispose();
        modificar.setVisible(true);
        this.pack();


    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void llenarTabla(ArrayList<RH_Empleado> lista) {
        String[] encabezado = {"IdEmpleado", "Nombre Completo" , "Departamento", "Puesto", "Ciudad", "Sucursal", "Turno"};
        Object[][] datos = new Object[lista.size()][7];
        int ren = 0;
        for (RH_Empleado s : lista) {
            datos[ren][0] = s.getIdEmpleado();
            datos[ren][1] = s.getNombreCompleto();
            datos[ren][2] = s.getDepartamento().getNombre();
            datos[ren][3] = s.getPuesto().getNombre();
            datos[ren][4] = s.getCiudad().getNombre();
            datos[ren][5] = s.getSucursal().getNombre();
            datos[ren][6] = s.getTurno().getNombre();
            ren++;
        }
        DefaultTableModel m = new DefaultTableModel(datos, encabezado) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }

        };

        tbl_Datos.setModel(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddEmpleado;
    private javax.swing.JPanel btn_Anterior;
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Siguiente;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorByte evaluatorByte1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_PaginaActual;
    private javax.swing.JLabel lbl_PaginaMaxima;
    private javax.swing.JTable tbl_Datos;
    // End of variables declaration//GEN-END:variables
}
