/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco Chavez
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    ConexionBD conexion;

    public PrincipalFrame(ConexionBD conexion) {
        this.conexion = conexion;
        initComponents();
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        lbl_fecha.setText(dateFormat.format(date));
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        lbl_User.setText(this.conexion.getName());
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        etiquetaReloj.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        evaluatorFloat1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorFloat();
        jPanel1 = new javax.swing.JPanel();
        btn_Ciudades = new javax.swing.JButton();
        btn_Deducciones = new javax.swing.JButton();
        btn_Turnos = new javax.swing.JButton();
        bnt_Estados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        etiquetaReloj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        btn_CerrarSesion = new javax.swing.JButton();
        btn_Empleados = new javax.swing.JButton();
        btn_Percepciones = new javax.swing.JButton();
        btn_Departamentos = new javax.swing.JButton();
        btn_Puestos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 151, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Ciudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ciudades.png"))); // NOI18N
        btn_Ciudades.setBorderPainted(false);
        btn_Ciudades.setContentAreaFilled(false);
        btn_Ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CiudadesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Ciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        btn_Deducciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Dedu.png"))); // NOI18N
        btn_Deducciones.setBorderPainted(false);
        btn_Deducciones.setContentAreaFilled(false);
        btn_Deducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeduccionesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Deducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        btn_Turnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Tur.png"))); // NOI18N
        btn_Turnos.setBorderPainted(false);
        btn_Turnos.setContentAreaFilled(false);
        btn_Turnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TurnosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Turnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        bnt_Estados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Estados.png"))); // NOI18N
        bnt_Estados.setBorderPainted(false);
        bnt_Estados.setContentAreaFilled(false);
        bnt_Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_EstadosActionPerformed(evt);
            }
        });
        jPanel1.add(bnt_Estados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 370, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Menú Principal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        etiquetaReloj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiquetaReloj.setText("hh:mm:ss");
        jPanel1.add(etiquetaReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Hora:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 660, -1, -1));

        lbl_fecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_fecha.setText("dd/mm/aaaa");
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Hola de nuevo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lbl_User.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(lbl_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 360, 100));

        btn_CerrarSesion.setText("Cerrar Sesion");
        btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, -1, -1));

        btn_Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Empleados.png"))); // NOI18N
        btn_Empleados.setToolTipText("");
        btn_Empleados.setBorderPainted(false);
        btn_Empleados.setContentAreaFilled(false);
        btn_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        btn_Percepciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Percepciones.png"))); // NOI18N
        btn_Percepciones.setBorderPainted(false);
        btn_Percepciones.setContentAreaFilled(false);
        btn_Percepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PercepcionesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Percepciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btn_Departamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Departamentos.png"))); // NOI18N
        btn_Departamentos.setBorderPainted(false);
        btn_Departamentos.setContentAreaFilled(false);
        btn_Departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DepartamentosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        btn_Puestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Puestos.png"))); // NOI18N
        btn_Puestos.setBorderPainted(false);
        btn_Puestos.setContentAreaFilled(false);
        btn_Puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PuestosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Puestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_EstadosActionPerformed
        EstadosFrame estados = new EstadosFrame(this.conexion);
        this.dispose();
        estados.setVisible(true);
        estados.pack();

    }//GEN-LAST:event_bnt_EstadosActionPerformed

    private void btn_CiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CiudadesActionPerformed
        CiudadesFrame ciudades = new CiudadesFrame(this.conexion);
        this.dispose();
        ciudades.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_CiudadesActionPerformed

    private void btn_TurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TurnosActionPerformed
        // TODO add your handling code here:
        TurnosFrame turno = new TurnosFrame(this.conexion);
        this.dispose();
        turno.setVisible(true);
        turno.pack();
    }//GEN-LAST:event_btn_TurnosActionPerformed

    private void btn_DeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeduccionesActionPerformed
        DeduccionesFrame deduccion = new DeduccionesFrame(this.conexion);
        this.dispose();
        deduccion.setVisible(true);
        deduccion.pack();
    }//GEN-LAST:event_btn_DeduccionesActionPerformed

    private void btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarSesionActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            login ventanaLogin = new login();
            this.dispose();
            ventanaLogin.setVisible(true);
            ventanaLogin.pack();
            JOptionPane.showMessageDialog(null, "Sesión Finalizada");
        }
    }//GEN-LAST:event_btn_CerrarSesionActionPerformed

    private void btn_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpleadosActionPerformed
        EmpleadosFrame empleados = new EmpleadosFrame(this.conexion);
        this.dispose();
        empleados.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_EmpleadosActionPerformed

    private void btn_DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DepartamentosActionPerformed
        DepartamentoFrame departamentos = new DepartamentoFrame(this.conexion);
        this.dispose();
        departamentos.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_DepartamentosActionPerformed

    private void btn_PercepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PercepcionesActionPerformed
        Percepciones percepcion = new Percepciones(this.conexion);
        this.dispose();
        percepcion.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_PercepcionesActionPerformed

    private void btn_PuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PuestosActionPerformed
        PuestosFrame puesto = new PuestosFrame(this.conexion);
        this.dispose();
        puesto.setVisible(true);
        this.pack();
    }//GEN-LAST:event_btn_PuestosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Estados;
    private javax.swing.JButton btn_CerrarSesion;
    private javax.swing.JButton btn_Ciudades;
    private javax.swing.JButton btn_Deducciones;
    private javax.swing.JButton btn_Departamentos;
    private javax.swing.JButton btn_Empleados;
    private javax.swing.JButton btn_Percepciones;
    private javax.swing.JButton btn_Puestos;
    private javax.swing.JButton btn_Turnos;
    private javax.swing.JLabel etiquetaReloj;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorFloat evaluatorFloat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JLabel lbl_fecha;
    // End of variables declaration//GEN-END:variables
}
