/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;

/**
 *
 * @author Marco Chavez
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    ConexionBD conexion;
    public PrincipalFrame(ConexionBD conexion) {
        this.conexion=conexion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Turnos = new javax.swing.JButton();
        bnt_Estados = new javax.swing.JButton();
        btn_Ciudades = new javax.swing.JButton();
        btn_Deducciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Turnos.setText("Turnos");
        btn_Turnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TurnosActionPerformed(evt);
            }
        });

        bnt_Estados.setText("Estados");
        bnt_Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_EstadosActionPerformed(evt);
            }
        });

        btn_Ciudades.setText("Ciudades");
        btn_Ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CiudadesActionPerformed(evt);
            }
        });

        btn_Deducciones.setText("Deducciones");
        btn_Deducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeduccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btn_Turnos)
                .addGap(73, 73, 73)
                .addComponent(btn_Ciudades)
                .addGap(54, 54, 54)
                .addComponent(bnt_Estados)
                .addGap(59, 59, 59)
                .addComponent(btn_Deducciones)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Turnos)
                    .addComponent(bnt_Estados)
                    .addComponent(btn_Ciudades)
                    .addComponent(btn_Deducciones))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_EstadosActionPerformed
       EstadosFrame estados = new EstadosFrame(this.conexion);
       this.dispose();
       estados.setVisible(true);
       estados.pack();
       
    }//GEN-LAST:event_bnt_EstadosActionPerformed

    private void btn_CiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CiudadesActionPerformed
       CiudadesFrame ciudades = new CiudadesFrame(this.conexion);
       this.dispose();
       ciudades.setVisible(true);
       this.pack();
    }//GEN-LAST:event_btn_CiudadesActionPerformed

    private void btn_TurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TurnosActionPerformed
        // TODO add your handling code here:
        Turnos turno = new Turnos (this.conexion);
        this.dispose();
        turno.setVisible(true);
        turno.pack();
    }//GEN-LAST:event_btn_TurnosActionPerformed

    private void btn_DeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeduccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeduccionesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Estados;
    private javax.swing.JButton btn_Ciudades;
    private javax.swing.JButton btn_Deducciones;
    private javax.swing.JButton btn_Turnos;
    // End of variables declaration//GEN-END:variables
}
