/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexion.ConexionBD;
import conexion.TurnosDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.RH_Turno;

/**
 *
 * @author selen
 */
public class Turnos extends javax.swing.JFrame {

    ConexionBD conexion;
    RH_Turno turno;
    Boolean bandera;

    /**
     * Creates new form Turnos
     */
    public Turnos(ConexionBD conexion) {
        this.conexion = conexion;
        initComponents();
//        TurnosDAO estados = new TurnosDAO(this.conexion);
//        ArrayList<RH_Turno> lista = estados.consultaTurnos();
//      cargarTabla(lista);

    }

    Turnos(ConexionBD conexion, RH_Turno turno) {
        this.turno = turno;
        this.conexion = conexion;

        btnguardar.setText("Modificar Turno");
        btnguardar.setEnabled(true);
        txtnombre.setText(this.turno.getNombre());
           
        String dias = null;
        if (rbLunes.isSelected() == true) {
            dias = "Lunes";

        }
        if (rbMartes.isSelected() == true) {
            dias = "Martes";
        }
        if (rbMiercoles.isSelected() == true) {
            dias = "Miercoles";
        }
        if (rbJueves.isSelected() == true) {
            dias = "Jueves";
        }
        if (rbViernes.isSelected() == true) {
            dias = "Viernes";
        }
        if (rbSabado.isSelected() == true) {
            dias = "Sabado";
        }
        if (rbDomingo.isSelected() == true) {
            dias = "Domingo";
        }
        this.bandera = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidTurno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthoraInicio = new javax.swing.JTextField();
        txthoraFin = new javax.swing.JTextField();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMiercoles = new javax.swing.JRadioButton();
        rbJueves = new javax.swing.JRadioButton();
        rbViernes = new javax.swing.JRadioButton();
        rbSabado = new javax.swing.JRadioButton();
        btnguardar = new javax.swing.JButton();
        rbDomingo = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turnos");
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(241, 151, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, 340));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/Turnos.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 110));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 31, 22));

        txtidTurno.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(txtidTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 64, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        txtnombre.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Inicio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Fecha Fin:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Días:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        txthoraInicio.setBackground(new java.awt.Color(153, 255, 153));
        txthoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraInicioActionPerformed(evt);
            }
        });
        jPanel2.add(txthoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 94, -1));

        txthoraFin.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.add(txthoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 97, -1));

        rbLunes.setBackground(new java.awt.Color(241, 151, 89));
        rbLunes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbLunes.setText("Lunes");
        jPanel2.add(rbLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        rbMartes.setBackground(new java.awt.Color(241, 151, 89));
        rbMartes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbMartes.setText("Martes");
        jPanel2.add(rbMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        rbMiercoles.setBackground(new java.awt.Color(241, 151, 89));
        rbMiercoles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbMiercoles.setText("Miercoles");
        jPanel2.add(rbMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        rbJueves.setBackground(new java.awt.Color(241, 151, 89));
        rbJueves.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbJueves.setText("Jueves");
        rbJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuevesActionPerformed(evt);
            }
        });
        jPanel2.add(rbJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        rbViernes.setBackground(new java.awt.Color(241, 151, 89));
        rbViernes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbViernes.setText("Viernes");
        rbViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViernesActionPerformed(evt);
            }
        });
        jPanel2.add(rbViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        rbSabado.setBackground(new java.awt.Color(241, 151, 89));
        rbSabado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbSabado.setText("Sabado");
        jPanel2.add(rbSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/btnGuardar.png"))); // NOI18N
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 160, 80));

        rbDomingo.setBackground(new java.awt.Color(241, 151, 89));
        rbDomingo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbDomingo.setText("Domingo");
        jPanel2.add(rbDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Turnos/btnAtras.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        RH_Turno eturno = new RH_Turno();
//int idTurno = Integer .parseInt(txtidTurno.getText());
//        String nombre = txtnombre.getText();
//        int horaInicio = Integer .parseInt(txthoraInicio.getText());
//        int horaFin = Integer .parseInt(txthoraFin.getText());
//        String dias = null;
        eturno.setNombre(txtnombre.getText().toUpperCase());
        eturno.setHoraInicio(Integer.parseInt(txthoraInicio.getText().toUpperCase()));
        eturno.setHoraFin(Integer.parseInt(txthoraFin.getText().toUpperCase()));
        String dias = null;
        if (rbLunes.isSelected() == true) {
            eturno.setDias("Lunes");

        }
        if (rbMartes.isSelected() == true) {
            eturno.setDias("Marte");
        }
        if (rbMiercoles.isSelected() == true) {
            eturno.setDias("Miercoles");
        }
        if (rbJueves.isSelected() == true) {
            eturno.setDias("Jueves");
        }
        if (rbViernes.isSelected() == true) {
            eturno.setDias("Viernes");
        }
        if (rbSabado.isSelected() == true) {
            eturno.setDias("Sabado");
        }
        if (rbDomingo.isSelected() == true) {
            eturno.setDias("Domindo");
        }
        TurnosDAO turnoDAO = new TurnosDAO(this.conexion);
        try {
//            Connection con = ConexionBD.GetConexion();
//            PreparedStatement ps =con.prepareStatement("INSERT INTO Turnos(idTurno,nombre,horaInicio,horaFin,dias) VALUES (?,?,?,?,?)");
//            ps.setInt(1, idTurno);
//            ps.setString(2, nombre);
//            ps.setInt(3, horaInicio);
//            ps.setInt(4,horaFin);
//            ps.setString(5,dias);
//            ps.executeUpdate();
//            JOptionPane.showMessageDialog(null, "Registro Guardado");
//            limpiar();
//            ArrayList<RH_Turno> lista = null;
//              cargarTabla(lista); 
            if (bandera) {
                eturno.setIdTurno(this.turno.getIdTurno());

                if (turnoDAO.actualizarTurno(eturno)) {
                    JOptionPane.showMessageDialog(null, "Estado Modificado con exito");
                    TurnoP turnos = new TurnoP(this.conexion);
                    this.dispose();
                    turnos.setVisible(true);
                    this.pack();
                }
            } else {
                if (turnoDAO.insertarTurno(eturno)) {
                    JOptionPane.showMessageDialog(null, "Estado Añadido con exito");
                    TurnoP turnos = new TurnoP(this.conexion);
                    this.dispose();
                    turnos.setVisible(true);
                    this.pack();
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error:" + e.getMessage());

//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Turnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void rbJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJuevesActionPerformed

    private void txthoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraInicioActionPerformed

    private void rbViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbViernesActionPerformed

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered

    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        EstadosFrame estados = new EstadosFrame(this.conexion);
        this.dispose();
        estados.setVisible(true);
        estados.pack();

    }//GEN-LAST:event_btnRegresarActionPerformed

//    private void cargarTabla(ArrayList<RH_Turno> lista){
//        
//        String[] encabezado = {"IdTurno", "nombre", "horaInicio", "horaFin", "dias"};
//        Object[][] datos = new Object[lista.size()][5];
//        int ren = 0;
//        for (RH_Turno s : lista) {
//            datos[ren][0] = s.getIdTurno();
//            datos[ren][1] = s.getNombre();
//            datos[ren][2] = s.getHoraInicio();
//            datos[ren][3] = s.getHoraInicio();
//            datos[ren][4]= s.getDias();
//            ren++;
//        }
//        
//      DefaultTableModel modeloTabla = new DefaultTableModel(datos, encabezado){
//               @Override
//            public boolean isCellEditable(int rowIndex, int colIndex) {
//                return false; //Disallow the editing of any cell
//            }
//
//      };
//                tblTurnos.getModel();
//      
//      
//        
//}
//    private void limpiar() {
//        txtidTurno.setText("");
//        txtidTurno.setText("");
//        txtidTurno.setText("");
//        txtidTurno.setText("");
//        txtidTurno.setText("");
//
//    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Turnos().setVisible(true);
//            }
//        });
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbDomingo;
    private javax.swing.JRadioButton rbJueves;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMiercoles;
    private javax.swing.JRadioButton rbSabado;
    private javax.swing.JRadioButton rbViernes;
    private javax.swing.JTextField txthoraFin;
    private javax.swing.JTextField txthoraInicio;
    private javax.swing.JTextField txtidTurno;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    

